language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libidn11-dev
      - libperl-dev
      - libssl-dev
      - gcc-5

sudo: false

compiler:
  - gcc-5
  - clang

env:
  - OPTIONAL_CONF_ARGS=""
  - OPTIONAL_CONF_ARGS="--with-perl"
  - OPTIONAL_CONF_ARGS="--enable-contrib"

script:
  - ./configure --disable-nls --enable-ssl --with-libidn $OPTIONAL_CONF_ARGS
  - make -j $(nproc)

matrix:
  fast_finish: true
  allow_failures:
    - env: OPTIONAL_CONF_ARGS="--enable-contrib"
